language: node_js
node_js:
  - '5.0'
sudo: required
services: docker
env:
 matrix:
   - MONGODB_VERSION=2.4
   - MONGODB_VERSION=2.6
   - MONGODB_VERSION=2.8
   - MONGODB_VERSION=3.0
   - MONGODB_VERSION=3.2
script:
 - npm run travis-ci
